language: node_js
node_js:
  - "12"
install:
  - cd backend
  - npm install
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: ZFmqtB583TMEbDX3EP6mQRXTzuZV81zBGa/m0/rw/pAwRUdPvnuW0TNzfku3xlmdKfMfPVibruCpmz4V08GAPPqJ85k3x/loA6LCOax58CkaXNXcbzPWsLjCwx4kYfDWahQLlhSD8KYePnAJj0NjrbfhQEev762K807bpUNgr76jNSD/Fry4PnFRO2Xn+DJR32daLFeNxJuu+dRLXX6vQz7oMhT+sHn9JRzA0FovIo0iXeVjdLSjYNRCpXAdLhEEdeTGGX5aUVe9kH0q4/g4WOv/uhLUTLAwrJ+miZKzFsKI3lBZx1sFbErvTX28d7uo0dhqgmG8dds7QRbSV624tq6Aa2PhC9xJ3JdKDLcNMHaQPwXjLvkYj6XDqMKYoD4b3sGvKNv3/EiQMAFNtOhUAlVzUSaFevZ91QISU54KR42da773cTsPcsB6TyAkcJDyI6Evo072YdK7CY/WhOOxUrKLXrzCBomFYH9UHFh2l9JoFax95HAgZ3PXPv7qkE2lWUiIYsrjvgXz/0ZpTxwa00pcotaL1h+VEfmMAScN7t3+Kd/cn6R9ThwQiJconqNPcQG1yK55H+3O5HEvuSyE31uigoo9aESF2sZvG/TNr6VFyGpcvJ+dWjvJlezuC6NOvVlk5p6y2fHDQsE5RjSuZ0hyI3QXGBaEMNwbpRu8fms=
  app: se-a1
