language: node_js
node_js:
- '12'
deploy:
  skip_cleanup: true
  provider: heroku
  api_key: #23ead3bc-11c0-4f7d-ad24-a0b27fef927e
    secure: FdW45az/Et1SZV3SndHT9Cein/Zmjn5IpkwYcX1e/x3sJg48u1BCMKcwNywp0/8KBwx9YSCXS3mjnGNq/TOx0xXsDEi2eX8NTYtx9xF/fJoPvpVxtFGvJFOuOpmwantT3hWuoXsl+B1rzqB/szsFb4q3A/uSloCKwAmlJYP6/jI6Q7HdHCE+XCQGMPRMYW2wJMxQGAei2pcmxP0hbrunOG118KaOxKnTAScUvzuFl6mCHyuWp0IKc0XdEJ+VHfJe1hhKLzcMKPS1y65HRQYQvCTNmMU7FjjZQu4EkZBNnx2Mk2blwRJCdUTnesOLgw6E2FRRziRRxDYRxa0Cx86YuyWxbNGgL+SQa0babz8D+fsgkTG/pHxUb156lUXH3pdiBjPeg6t1xgWGGK4cqFRxXg/uehW63UeDi9/LmbLGwZT6VzGGil82uCivJKOha6bf5OMRzUsjCmpZoi1wmLpnnzKcmaJBBnHsTIpWo5+R9M7V/7ImhqRkx/nvtPSBxs5aKO6h77iJPm+Ske3VbdQGll3MN77SILOC0/woxdO8WlI4cftQXhvbGdrdrG83hEdVOdOtXAFZPvNeWTomiKsrIQjsCk9NyaHut1PGnDtTPMIVBB2dAYlEgf5JrLGzmE0vRNiTTc8hWR76T9azJA6OHGlkMlcsa6IQiMnsB6KzAaE=
  app: se-a1
